@isTest
public class RecordTypeHelperTest {
    @isTest
    static void test()
    {
        String test = '';
        test = RecordTypeHelper.ORDER_DELIVARY_ORDER;
        test = RecordTypeHelper.ORDER_TRANSFER_ORDER;
        test = RecordTypeHelper.ORDER_PURSCHASE_ORDER;
        test = RecordTypeHelper.ORDER_SALES_ORDER;
        test = RecordTypeHelper.TRANSACTION_HEADER_IMPORT;
        test = RecordTypeHelper.TRANSACTION_HEADER_EXPORT;
        test = RecordTypeHelper.TRANSACTION_HEADER_TRANSFER;
        test = RecordTypeHelper.ACOUNT_DOI_TAC_DAI_LY;
        test = RecordTypeHelper.DISTRICT;
        test = RecordTypeHelper.PROVINCE;
        test = RecordTypeHelper.WARD;
        test = RecordTypeHelper.ASSET_GROUP;
        test = RecordTypeHelper.PRODUCT;
        test = RecordTypeHelper.PRODUCT_PRICE;
        test = RecordTypeHelper.SALES_PLAN;
        test = RecordTypeHelper.SALES_REP;
        test = RecordTypeHelper.MASTER_DATA_WAREHOUSE;
        test = RecordTypeHelper.REGION;
        test = RecordTypeHelper.MASTER_DATA_WAREHOUSE_LOCATION;
        test = RecordTypeHelper.MASTER_DATA_WAREHOUSE_INVENTORY;
        test = RecordTypeHelper.TERRITORY;
        test = RecordTypeHelper.TERRITORY_SETUP;
        test = RecordTypeHelper.PROMOTION;
        test = RecordTypeHelper.ACCOUNT_ADDRESS;
        test = RecordTypeHelper.DEFAULT_RECORD;
        test = RecordTypeHelper.PRODUCT_PRICE_ITEM;
		test = RecordTypeHelper.TERRITORY_ASSIGNMENT;
        test = RecordTypeHelper.TERRITORY_RULE;
        test = RecordTypeHelper.USER_HIERACHY;       
        test = RecordTypeHelper.DELIVERY_ORDER;
        test = RecordTypeHelper.INVENTORY_TRANSACTION_HEADER;
        test = RecordTypeHelper.INVENTORY_TRANSACTION_HEADER_IMPORT; 
        test = RecordTypeHelper.INVENTORY_TRANSACTION_HEADER_EXPORT;
        test = RecordTypeHelper.INVENTORY_TRANSACTION_HEADER_TRANSFER;
        test = RecordTypeHelper.ORDER;  
        test = RecordTypeHelper.PURCHASE_ORDER;  
        test = RecordTypeHelper.QUOTA_PLAN; 
        test = RecordTypeHelper.RETURN_ORDER; 
        test = RecordTypeHelper.SALES_ORDER; 
        test = RecordTypeHelper.TRANSFER_ORDER; 
        test = RecordTypeHelper.LEAD; 
        test = RecordTypeHelper.ORDER_ITEM; 
        test = RecordTypeHelper.QUOTA_PLAN_ITEM;
        test = RecordTypeHelper.QUOTA_PLAN_ITEM_MONTH;
        test = RecordTypeHelper.TRANSACTION_ITEM_LOCATION;
        test = RecordTypeHelper.ASSET_TRANSACTION;
        test = RecordTypeHelper.INVENTORY_TRANSACTION_ITEM;
    }
}